---
title: "afte_paper_code"
output: html_document
---


We are first starting with the "hamby44_eval" file, which has the column "rlo_resid" already calculated, using my (Kiegan's) updated robust loess function.  


```{r packages-and-data, echo = F, message = F, warning = F}
library(devtools)
#install.packages("tidyverse")
#library(tidyverse)
library(tidyr)
library(dplyr)
library(purrr)
library(ggplot2)

#hamby44 <- readRDS("//opt/hamby44/hamby44.rda") ## this gives the whole thing, we just want to focus on the`ccdata`.
#hamby44[1:6,]

hamby44 <- readRDS("data/hamby44/hamby44_eval.rda")
hamby44[1:6,]
```


```{r define-robust_loess_fit, echo = F, warning = F, message = F}
robust_loess_fit <- function(bullet, iter){
  n <- nrow(bullet)
  weights <- rep(1, n)
  fit <- loess(value_std~x, data = bullet, span = 1)
  bullet$fit <- predict(fit, newdata = bullet)
  bullet$resid <- bullet$value_std - bullet$fit
  i <- 1
  while(i < iter){
    mar <- median(abs(bullet$resid), na.rm = T)
    bullet$bisq <- pmax(1 - (bullet$resid/(6*mar))^2, 0)^2
    weights <- ifelse(bullet$resid > 0 , bullet$bisq, 1)
    fit <- loess(value_std~x, data = bullet, span = 1, weights = weights)
    bullet$fit <- predict(fit, newdata = bullet)
    bullet$resid <- bullet$value_std - bullet$fit
    i <- i+1
  }
  return(fit)
}
```

```{r define-get_grooves_mad, echo = F, warning = F, message = F}

get_grooves_mad <- function(bullet, adjust, multiplier){
  rlm0 <- robust_loess_fit(bullet, iter = 30)
  bullet$rlo_pred <- predict(rlm0, newdata=bullet)
  bullet$rlo_resid <- with(bullet, value_std - rlo_pred)
  bullet$rlo_absresid <- with(bullet, abs(value_std - rlo_pred))
  
  #bullet %>% ggplot() + geom_point(aes(x = y, y = resid)) + theme_bw()
  #bullet %>% ggplot() + geom_point(aes(x = y, y = resid_div)) + theme_bw()
  mad1 <- mad(bullet$rlo_resid, na.rm = T)
  bullet$resid_cutoff <- with(bullet, rlo_absresid > mad1*multiplier)
  groove <- range(filter(bullet, !resid_cutoff)$x) + c(adjust, -adjust)
  
  plot <- bullet %>% ggplot(aes(x = y, y = value_std)) + geom_line(size = .5) + theme_bw() +
    geom_vline(xintercept=groove[1], colour = "blue") +
    geom_vline(xintercept=groove[2], colour = "blue") 
  
  return(list(groove = groove, plot = plot))
}

get_grooves_mad_rlm <- function(bullet, adjust, multiplier){
  lm0 <- MASS::rlm(value_std~poly(x,2), data=bullet, maxit=100)
  bullet$rlm_pred <- predict(lm0, newdata=bullet)
  bullet$rlm_resid <- with(bullet, value_std - rlm_pred)
  bullet$rlm_absresid <- with(bullet, abs(value_std - rlm_pred))
  
  #bullet %>% ggplot() + geom_point(aes(x = y, y = resid)) + theme_bw()
  #bullet %>% ggplot() + geom_point(aes(x = y, y = resid_div)) + theme_bw()
  mad1 <- mad(bullet$rlm_resid, na.rm = T)
  bullet$resid_cutoff <- with(bullet, rlm_absresid > mad1*multiplier)
  groove <- range(filter(bullet, !resid_cutoff)$x) + c(adjust, -adjust)
  
  plot <- bullet %>% ggplot(aes(x = y, y = value_std)) + geom_line(size = .5) + theme_bw() +
    geom_vline(xintercept=groove[1], colour = "blue") +
    geom_vline(xintercept=groove[2], colour = "blue") 
  
  return(list(groove = groove, plot = plot))
}

```


```{r define-get_grooves_mar, echo = F, warning = F, message = F}
get_grooves_mar <- function(bullet, adjust, multiplier){
  rlm0 <- robust_loess_fit(bullet, iter = 30)
  bullet$rlo_pred <- predict(rlm0, newdata=bullet)
  bullet$rlo_resid <- with(bullet, value_std - rlo_pred)
  bullet$rlo_absresid <- with(bullet, abs(value_std - rlo_pred))
  
  #bullet %>% ggplot() + geom_point(aes(x = y, y = resid)) + theme_bw()
  #bullet %>% ggplot() + geom_point(aes(x = y, y = resid_div)) + theme_bw()
  mar1 <- median(bullet$rlo_absresid, na.rm = T)
  bullet$resid_cutoff <- with(bullet, rlo_absresid > mar1*multiplier)
  groove <- range(filter(bullet, !resid_cutoff)$x) + c(adjust, -adjust)
  
  plot <- bullet %>% ggplot(aes(x = y, y = value_std)) + geom_line(size = .5) + theme_bw() +
    geom_vline(xintercept=groove[1], colour = "blue") +
    geom_vline(xintercept=groove[2], colour = "blue") 
  
  return(list(groove = groove, plot = plot))
}

```

```{r run-get_grooves_mad, echo = F, warning = F, message = F}

hamby44 <- hamby44 %>% mutate(grooves_pred_mad2 = purrr::map(ccdata_w_resid, .f = function(bullet){
 grooves <- get_grooves_mad(bullet, adjust = 5, multiplier = 2)$groove 
 return(grooves)
}))

```

```{r run-get_grooves_mar, echo = F, warning = F, message = F}
hamby44 <- hamby44 %>% mutate(grooves_pred_mar2 = purrr::map(ccdata_w_resid, .f = function(bullet){
  grooves <- get_grooves_mar(bullet, adjust = 5, multiplier = 2)$groove
  return(grooves)
}))
```

```{r run-get_grooves_mad4, echo = F, warning = F, message = F}
hamby44 <- hamby44 %>% mutate(grooves_pred_mad4 = purrr::map(ccdata_w_resid, .f = function(bullet){
  grooves <- get_grooves_mad(bullet, adjust = 5, multiplier = 4)$groove
  return(grooves)
}))
```


```{r run-get_grooves_mad_rlm, echo = F, warning = F, message = F}
hamby44 <- hamby44 %>% mutate(grooves_pred_mad2rlm = purrr::map(ccdata_w_resid, .f = function(bullet){
 grooves <- get_grooves_mad_rlm(bullet, adjust = 5, multiplier = 2)$groove 
 return(grooves)
}))
hamby44 <- hamby44 %>% mutate(grooves_pred_mad4rlm = purrr::map(ccdata_w_resid, .f = function(bullet){
 grooves <- get_grooves_mad_rlm(bullet, adjust = 5, multiplier = 4)$groove 
 return(grooves)
}))
```

```{r predictions-evaluation, echo = F, warning = F, message = F}
prediction_scores <- function(dataset, method){
  colname <- paste0("grooves_pred_", method)
  new_colname <- paste0("score_left_", method)
  new_colname2 <- paste0("score_right_", method)
  dataset[,new_colname] <- 0
  dataset[,new_colname2] <- 0
  for(i in 1:nrow(dataset)){
    bullet <- dataset[i,]
    left_pred <- bullet[,colname][[1]][[1]][1]
    left_groove <- as.numeric(bullet[,"left_groove"])
    dat <- bullet$ccdata_w_resid[[1]]
    dat <- dat %>% filter(between(y, min(left_pred, left_groove), max(left_pred, left_groove)))
    dataset[i,new_colname] <- sum(dat$rlo_resid, na.rm = T)
    
    right_pred <- bullet[,colname][[1]][[1]][2]
    right_groove <- as.numeric(bullet[,"right_groove"])
    dat2 <- bullet$ccdata_w_resid[[1]]
    dat2 <- dat2 %>% filter(between(y, min(right_pred, right_groove), max(right_pred, right_groove)))
    dataset[i, new_colname2] <- sum(dat2$rlo_resid, na.rm = T)
  }
  return(dataset)
}


hamby44_eval <- prediction_scores(hamby44, "mad2")
hamby44_eval <- prediction_scores(hamby44_eval, "mar2")
hamby44_eval <- prediction_scores(hamby44_eval, "mad4")
hamby44_eval <- prediction_scores(hamby44_eval, "mad2rlm")
hamby44_eval <- prediction_scores(hamby44_eval, "mad4rlm")
head(hamby44_eval)
```


```{r plot-scores-functions, echo = F, warning = F, message = F}
plot_scores <- function(dataset, methods = NULL){
  colnames <- c()
  for (i in 1:length(methods)){
    colnames <- c(colnames, paste0("score_left_", methods[i]))
    colnames <- c(colnames, paste0("score_right_", methods[i]))
  }
  plot_df <- dataset %>% ungroup() %>% 
    select(colnames) %>%  
    gather(method, score) %>% 
    mutate(GrooveMethod = unlist(purrr::map(method, .f = function(x){
      strsplit(x, "_")[[1]][3]
        })), GrooveSide = unlist(purrr::map(method, .f = function(x){
      strsplit(x, "_")[[1]][2]
        }))
    )
  plot_df %>% 
    ggplot() + geom_boxplot(aes(x = GrooveSide, y = abs(score), fill = GrooveMethod)) + 
      theme_bw() + labs(x = "Groove Side", y = "Inaccuracy Score")
}

plot_scores_zoom <- function(dataset, zoom_cutoff, methods = NULL){
  colnames <- c()
  for (i in 1:length(methods)){
    colnames <- c(colnames, paste0("score_left_", methods[i]))
    colnames <- c(colnames, paste0("score_right_", methods[i]))
  }
  plot_df <- dataset %>% ungroup() %>% 
    select(colnames) %>%  
    gather(method, score) %>% 
    mutate(GrooveMethod = unlist(purrr::map(method, .f = function(x){
      strsplit(x, "_")[[1]][3]
        })), GrooveSide = unlist(purrr::map(method, .f = function(x){
      strsplit(x, "_")[[1]][2]
        }))
    ) %>% 
    filter(score < zoom_cutoff)
  plot_df %>% 
    ggplot() + geom_boxplot(aes(x = GrooveSide, y = abs(score), fill = GrooveMethod)) + 
      theme_bw() + labs(x = "Groove Side", y = "Inaccuracy Score")
  }
```




```{r plot_scores}
plot_scores(hamby44_eval, methods = c("mar2", "mad2", "mad4", "mad2rlm", "mad4rlm"))

plot_scores_zoom(hamby44_eval, zoom_cutoff = 5000, methods = c("mar2", "mad2", "mad4", "mad2rlm", "mad4rlm"))
```





```{r, echo = F, warning = F, message = F}
plot_scores(hamby44_eval, methods = c("mar2", "mad2", "mad4"))
plot_scores(hamby44_eval, methods = c("logistic", "mad4"))
plot_scores(hamby44_eval, methods = c("rollapply", "mad4"))
plot_scores(hamby44_eval, methods = c("rollapply", "mad4rlm", "mad2"))
plot_scores_zoom(hamby44_eval, methods = c("rollapply", "mad4rlm", "mad2"), zoom_cutoff = 5000)

hamby44_eval %>% ggplot() + geom_point(aes(x = score_right_mad2, y = score_right_rollapply)) + theme_bw() + geom_abline() + coord_equal()
#+ ylim(c(NA,3000))
```


```{r score-medians, echo = F, warning = F, message = F}
median(hamby44_eval$score_left_mad2)
median(hamby44_eval$score_right_mad2)
median(hamby44_eval$score_left_mad4)
median(hamby44_eval$score_right_mad4)
```


```{r, echo = F, warning = F, message = F}
plot_categories <- function(dataset, methods = NULL){
  colnames <- c()
  for (i in 1:length(methods)){
    colnames <- c(colnames, paste0("score_left_", methods[i]))
    colnames <- c(colnames, paste0("score_right_", methods[i]))
  }
  plot_df <- dataset %>% ungroup() %>% 
    select(colnames) %>%  
    gather(method, score) %>% 
    mutate(GrooveMethod = unlist(purrr::map(method, .f = function(x){
      strsplit(x, "_")[[1]][3]
        })), GrooveSide = unlist(purrr::map(method, .f = function(x){
      strsplit(x, "_")[[1]][2]
        }))
    ) %>% mutate(AccuracyCategory = ifelse(abs(score) < 100, "<100", "100, 1000")) %>% 
    mutate(AccuracyCategory = ifelse(abs(score) >= 1000, ">1000", AccuracyCategory))
  
  plot_df$GrooveLabels <- ifelse(plot_df$GrooveSide=="left", "left shoulder location", "right shoulder location")
  plot_df %>% 
    ggplot() + geom_bar(aes(x = GrooveMethod, fill=factor(AccuracyCategory, levels=c(">1000","100, 1000", "<100"))), position = "stack") + 
      theme_bw() + labs(x = "Groove Method", y = "Number of Lands") + 
    facet_wrap(~GrooveLabels ) + 
    scale_fill_manual(name="Inaccuracy Score", values=c("#999999", "#E69F00", "#56B4E9"),
                         breaks=c(">1000", "100, 1000", "<100"),
                         labels=c("Greater than 1000", "Between 100 and 1000", "Less than 100"))
}

plot_categories(hamby44_eval, methods = c("rollapply", "mad4", "mad4rlm"))

saveRDS(hamby44_eval, file = "../data/hamby44/hamby44_eval_paper.rda")
```